// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: proto2_test.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proto2Message_EnumType int32

const (
	Proto2Message_UNKNOWN Proto2Message_EnumType = 0
	Proto2Message_VALUE1  Proto2Message_EnumType = 1
	Proto2Message_VALUE2  Proto2Message_EnumType = 2
)

// Enum value maps for Proto2Message_EnumType.
var (
	Proto2Message_EnumType_name = map[int32]string{
		0: "UNKNOWN",
		1: "VALUE1",
		2: "VALUE2",
	}
	Proto2Message_EnumType_value = map[string]int32{
		"UNKNOWN": 0,
		"VALUE1":  1,
		"VALUE2":  2,
	}
)

func (x Proto2Message_EnumType) Enum() *Proto2Message_EnumType {
	p := new(Proto2Message_EnumType)
	*p = x
	return p
}

func (x Proto2Message_EnumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Proto2Message_EnumType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto2_test_proto_enumTypes[0].Descriptor()
}

func (Proto2Message_EnumType) Type() protoreflect.EnumType {
	return &file_proto2_test_proto_enumTypes[0]
}

func (x Proto2Message_EnumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Proto2Message_EnumType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Proto2Message_EnumType(num)
	return nil
}

// Deprecated: Use Proto2Message_EnumType.Descriptor instead.
func (Proto2Message_EnumType) EnumDescriptor() ([]byte, []int) {
	return file_proto2_test_proto_rawDescGZIP(), []int{0, 0}
}

type Proto2Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *string                      `protobuf:"bytes,1,req,name=required_field,json=requiredField" json:"required_field,omitempty"`
	OptionalField *string                      `protobuf:"bytes,2,opt,name=optional_field,json=optionalField,def=default value" json:"optional_field,omitempty"`
	RepeatedField []int32                      `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	Nested        *Proto2Message_NestedMessage `protobuf:"bytes,4,opt,name=nested" json:"nested,omitempty"`
	EnumField     *Proto2Message_EnumType      `protobuf:"varint,5,opt,name=enum_field,json=enumField,enum=test.Proto2Message_EnumType,def=1" json:"enum_field,omitempty"`
}

// Default values for Proto2Message fields.
const (
	Default_Proto2Message_OptionalField = string("default value")
	Default_Proto2Message_EnumField     = Proto2Message_VALUE1
)

func (x *Proto2Message) Reset() {
	*x = Proto2Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proto2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2Message) ProtoMessage() {}

func (x *Proto2Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2Message.ProtoReflect.Descriptor instead.
func (*Proto2Message) Descriptor() ([]byte, []int) {
	return file_proto2_test_proto_rawDescGZIP(), []int{0}
}

func (x *Proto2Message) GetRequiredField() string {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return ""
}

func (x *Proto2Message) GetOptionalField() string {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Proto2Message_OptionalField
}

func (x *Proto2Message) GetRepeatedField() []int32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Proto2Message) GetNested() *Proto2Message_NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Proto2Message) GetEnumField() Proto2Message_EnumType {
	if x != nil && x.EnumField != nil {
		return *x.EnumField
	}
	return Default_Proto2Message_EnumField
}

type Proto2Message_NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InnerField *string `protobuf:"bytes,1,opt,name=inner_field,json=innerField" json:"inner_field,omitempty"`
}

func (x *Proto2Message_NestedMessage) Reset() {
	*x = Proto2Message_NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proto2Message_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2Message_NestedMessage) ProtoMessage() {}

func (x *Proto2Message_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2Message_NestedMessage.ProtoReflect.Descriptor instead.
func (*Proto2Message_NestedMessage) Descriptor() ([]byte, []int) {
	return file_proto2_test_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Proto2Message_NestedMessage) GetInnerField() string {
	if x != nil && x.InnerField != nil {
		return *x.InnerField
	}
	return ""
}

var File_proto2_test_proto protoreflect.FileDescriptor

var file_proto2_test_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0xf6, 0x02, 0x0a, 0x0d, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x34, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x0d, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x39, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x43, 0x0a, 0x0a, 0x65, 0x6e,
	0x75, 0x6d, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x06, 0x56, 0x41,
	0x4c, 0x55, 0x45, 0x31, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a,
	0x30, 0x0a, 0x0d, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x22, 0x2f, 0x0a, 0x08, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x41,
	0x4c, 0x55, 0x45, 0x31, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x32,
	0x10, 0x02, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x66, 0x72, 0x69, 0x64, 0x6d, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x6a, 0x73, 0x6f, 0x6e, 0x2f, 0x74, 0x65, 0x73,
	0x74,
}

var (
	file_proto2_test_proto_rawDescOnce sync.Once
	file_proto2_test_proto_rawDescData = file_proto2_test_proto_rawDesc
)

func file_proto2_test_proto_rawDescGZIP() []byte {
	file_proto2_test_proto_rawDescOnce.Do(func() {
		file_proto2_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto2_test_proto_rawDescData)
	})
	return file_proto2_test_proto_rawDescData
}

var file_proto2_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto2_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto2_test_proto_goTypes = []interface{}{
	(Proto2Message_EnumType)(0),         // 0: test.Proto2Message.EnumType
	(*Proto2Message)(nil),               // 1: test.Proto2Message
	(*Proto2Message_NestedMessage)(nil), // 2: test.Proto2Message.NestedMessage
}
var file_proto2_test_proto_depIdxs = []int32{
	2, // 0: test.Proto2Message.nested:type_name -> test.Proto2Message.NestedMessage
	0, // 1: test.Proto2Message.enum_field:type_name -> test.Proto2Message.EnumType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto2_test_proto_init() }
func file_proto2_test_proto_init() {
	if File_proto2_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto2_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proto2Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proto2Message_NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto2_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto2_test_proto_goTypes,
		DependencyIndexes: file_proto2_test_proto_depIdxs,
		EnumInfos:         file_proto2_test_proto_enumTypes,
		MessageInfos:      file_proto2_test_proto_msgTypes,
	}.Build()
	File_proto2_test_proto = out.File
	file_proto2_test_proto_rawDesc = nil
	file_proto2_test_proto_goTypes = nil
	file_proto2_test_proto_depIdxs = nil
}
